### ISSUE TITLE
alter table *.* set next_trid doesn't work when row already inserted

### ISSUE THREAD

**Issue by niolap** [siodb/siodb#117]
```sql
siocli> create table db1.test1 ( col text ) ;

Command execution time: 1362 ms.

siocli> alter table db1.test1 set next_trid = 2 ;

Command execution time: 1 ms.

siocli> alter table db1.test1 set next_trid = 9999;    ------------------------> works OK

Command execution time: 0 ms.

siocli> insert into db1.test1 values ('qsdqsdd') ;

1 rows affected
Command execution time: 7739 ms.

siocli> alter table db1.test1 set next_trid = 999 ;   ------------------------> works as expected

Status 2112: Invalid next user TRID 999 for the table 'DB1'.'TEST1'

Command execution time: 0 ms.

siocli> select * from db1.test1 ;
TRID                COL
------------------- ----------------------------------------
               9999 qsdqsdd

1 rows.
Command execution time: 14 ms.

siocli> alter table db1.test1 set next_trid = 1001 ;  ------------------------> should works

Status 2112: Invalid next user TRID 1001 for the table 'DB1'.'TEST1'
```

**Comment by cxxman** [comment]
This is correct behaviour. Look into original issue https://github.com/siodb/siodb/issues/49 , it says :
NOTES: 
- The command `ALTER TABLE x SET NEXT_TRID = y ;` should not permit to set the TRID to a value <= the last generated TRID.

**Comment by niolap** [comment]
@cxxman yes but in the example described in the first post you can see that I set the TRID (last command) to a value (1001) > to the last generated TRID (which should be 1000). Thus this should work, isn't?

**Comment by cxxman** [comment]
No, incorrect, "last generated TRID" is 9999. It was generated at last INSERT. You cannot set TRID lower than it.

**Comment by niolap** [comment]
@cxxman Yes but that one should works  (because last TRID is 9999):

```sql
siocli> alter table db1.test1 set next_trid = 1001 ;  ------------------------> should works

Status 2112: Invalid next user TRID 1001 for the table 'DB1'.'TEST1'
```
Any case it doesn't work for all number > 1000.

**Comment by IvanPizhenko** [comment]
1001 is less than 9999, so it must not work and doesn't work, that's correct

**Comment by cxxman** [comment]
1001 is less than 9999, so it must not work, but any numbers greater than 9999 should work

**Comment by niolap** [comment]
@cxxman sorry was not 9999 but 999 in my example above. So still the same question but with 999.

**Comment by cxxman** [comment]
In all your above examples it is exactly  9999, not 999. Anyway, will recheck now.

**Comment by cxxman** [comment]
Rechecked, works exactly as you've described, and that is correct, because last generated (at insert) TRID is 9999 and next cannot be less or equal to that.

**Comment by niolap** [comment]
@cxxman Recheck and it works, I figured out that my check was totally wrong
