### ISSUE TITLE
Rename table doesn't works as expected

### ISSUE THREAD

**Issue by niolap** [siodb/siodb#118]
Currently, an error stating that the name is invalid it printed but with the wrong table name and nothing happens:

```sql
siocli> alter table test1 rename to test2 ;

Status 2031: Invalid table name 'TEST1'

Command execution time: 0 ms.
```

If the rename table is supported, it should rename the table. If not yet supported, then the default message should be printed "not supported yet".

**Comment by cxxman** [comment]
It has never worked, it is not implemented yet. So actually new feature.

**Comment by cxxman** [comment]
There is issue #11 for RENAME TABLE. Closing this one.
