### ISSUE TITLE
SQL Query through REST

### ISSUE THREAD

**Issue by niolap** [siodb/siodb#133]
Siodb must provide query through REST to give users the option to get only the needed data instead of the whole table resultset that we have with a GET on a table. Here is the specification:

The existing SQL parser will be used to parse queries but the dataset will be processed by the REST handler.

### Path and REST verb

**Verb:** GET
**Path:** <>/query

### Payload

- query: the query. Only queries allowed (no DDL, DML). 

```json
[{
	"query": "select users.username, users.email, orders.id, orders.date, orders.amount from users, orders where users.trid = orders.user_trid and users.user_trid in ( 31, 32, 33 ) and users.status = 1"
}]
```

### Return

```json
{
	"users": [{
		"username": "usr_name_1",
		"email": "usr_name_1@gmail.com",
		"orders": [{
			"id": 2543,
			"date": "2020.08.11",
			"amount": 35.99
		}, {
			"id": 2843,
			"date": "2020.10.01",
			"amount": 45.99
		}, {
			"id": 3843,
			"date": "2020.12.23",
			"amount": 395.99
		}]
	}, {
		"username": "usr_name_2",
		"email": "usr_name_2@gmail.com",
		"orders": [{
			"id": 3815,
			"date": "2021.01.11",
			"amount": 35.99
		}, {
			"id": 3176,
			"date": "2021.02.03",
			"amount": 45.99
		}, {
			"id": 3898,
			"date": "2020.03.05",
			"amount": 395.99
		}]
	}]
}
```

**Comment by cxxman** [comment]
I think "query_name" is not necessary. Queries already go in the certain order and responses will go in the same order.

**Comment by niolap** [comment]
@cxxman yes not really necessary. I removed it.

**Comment by cxxman** [comment]
Next thing - GET request does not support sending payload separately like in POST or PUT. Get request can only accept parameters through URL. Despite a bit different REST-specific meaning, I think in this case you need to use POST.

**Comment by niolap** [comment]
@cxxman it has been difficult to choose between GET and POST for this reason. This feature aims to get data and in rfc7231 I understand that for GET is up to the application to accept payload. It makes more sense to have it in a GET but it's not really defined as a standard, true. Then we can:

- Use POST + payload: but posting a query seems a bit weird to me. Because POST is more use to create things. We could say that we create a query (and later a set of queries)
- Use GET with query(ies) as parameters: but this may be let elegant, especially with huge query

**Comment by cxxman** [comment]
Please consider that typically HTTP clients do not support sending payload in GET. So I'd vote for the POST+payload. It is more natural. But alternatively you may have GET formed as follows:
Single query:
```
https://server:port/query?q=....
```
or
```
https://server:port/query?q1=....
```
Multiple queries:
```
https://server:port/query?q1=....&q2=.....&q3=.....
```

**Comment by niolap** [comment]
Let's first offer GET with query parameter as you mentioned:

`https://server:port/query?q=....`

Then, we can extend it to multiple queries in another task and maybe offer POST with payload in the future.

**Comment by cxxman** [comment]
ok

**Comment by niolap** [comment]
@cxxman tested a bit and I think we have a regression. For instance now, the REST GET request on a table returns a table not exist error, even when the table exists:

```bash
$ ./build/release/bin/siocli -i ./tests/share/private_key --user root -r
Siodb SQL Client v.0.10.0
Compiled on May 31 2021 13:36:03
Copyright (C) 2019-2021 Siodb GmbH. All rights reserved.

siocli> select * from db1.table1 ;

Connected to localhost:50000

TRID                COL1
------------------- ----------------------------------------

Row(s): 0

Elapsed time: 14 ms.
```

And the result from curl:

```bash
curl -k https://root:${TOKEN}@localhost:50443/databases/db1/tables/table1/rows
```

Returns:

```bash
{"status":404,"rows":[]}
```

A few commits ago it returned 200. I know it because the test `tests/scenarios/rest_codes_returned/run.sh` was running successfully. And now it's not working anymore.

But if I insert a row, now I have a code 200.  So I think we should get back to the previous code 200 when no row exists. Because it returns a result set of no row successfully. It is just that there is no row.

**Comment by cxxman** [comment]
@niolap moved your comment into the separate issue #158

**Comment by niolap** [comment]
@cxxman The error return from IOMgr to REST server is 0 when SQL has error. I think the error code is never handle for REST `set_rest_status_code` in `RequestHandler::executeSelectRequest`:

```bash
curl -k -w "%{http_code}"  https://root:xxx@localhost:50443/query?q='select t.name tname, c.name cname from sys_tables t, sys_columns c where t.trid = c.tablze_id' 
```

Returns

```json
{"status":0, "error":"code: 2062, message: SELECT: Column 'C'.'TABLZE_ID' is unknown"}
```

I think it should return 400.

Just pushed a commit to include "status" in JSON from REST server Go program (in the same logic as the IOMgr). It was not the case before.

EDIT: created issue gh-163 for this

**Comment by niolap** [comment]
@cxxman from my point of view, all bugs are cleared then we can close this issue if ok for you
