### ISSUE TITLE
Upgrade all 3rd party libraries to actual versions

### ISSUE THREAD

**Issue by niolap** [siodb/siodb#134]
Update versions:
- [x] antlr 4.8 -> 4.9.2 (+manually link to utf8cpp 3.1.2)
- [x] date 20190911 -> 3.0.1 (take latest git) 
- [x] googletest 1.8.1 -> 1.10.0
- [x] openssl 1.1.1g -> 1.1.1k
- [x] protobuf 3.12.3 -> 3.15.6
- [x] utf8cpp 3.1.1 -> 3.1.2
- [x] xxhash 0.7.2 -> 0.8.0

Remove:
- [x] oatpp 1.1.0 (not used)

Ensure build:
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04 
- [x] CentOS 7
- [x] CentOS 8
- [ ] ??? Rocky Linux (when beta available)

**Comment by cxxman** [comment]
Made it in Ubuntu 18.04 but need to recheck in the CentOS 7.

**Comment by cxxman** [comment]
@niolap Please check if it build on all platforms, and if so - close this issue

**Comment by niolap** [comment]
@cxxman compilation and tests passed on all supported platforms
