### ISSUE TITLE
Properly convert multibyte UTF-8 sequences to JSON

### ISSUE THREAD

**Issue by cxxman** [siodb/siodb#149]
Speaking generally, what we do here, even after such fixes, still not completely correct, because we would have generated byte-per-byte encoding for valid multibyte UTF-8 sequences, which is not correct, because they must be either one or two `\uXXXX` (see [RFC 7159](https://tools.ietf.org/html/rfc7159) Section 7). But I suggest to do this as a separate fix.

_Originally posted by @cxxman in https://github.com/siodb/siodb/pull/148#discussion_r619690051_

**Comment by niolap** [comment]
In this same RFC, we can see that:
   "_Alternatively, there are two-character sequence escape
   representations of some popular characters.  So, for example, a
   string containing only a single reverse solidus character may be
   represented more compactly as "\\"._"
Thus, reverse solidus are ok to have compact a compact form of escaping. Thus, this one is not critical right now and will be implemented in a later milestone.

**Comment by cxxman** [comment]
Hmm. What about having things like [this](http://www.unicode.org/emoji/charts/full-emoji-list.html) in the text? Nowadays emoji easily appear in the lots of emails and chat messages. Failing to transfer them properly as JSON may be a big deal.

**Comment by cxxman** [comment]
Moreover, it's not something that hard to fix. So I'd suggest to include it into 0.10.

**Comment by niolap** [comment]
> Hmm. What about having things like [this](http://www.unicode.org/emoji/charts/full-emoji-list.html) in the text? Nowadays emoji easily appear in lots of emails and chat messages. Failing to transfer them properly as JSON may be a big deal.

@cxxman it works:
```bash
# Inserting from siocli and comparing with REST Get:
SIOCLI(SUCCESS) | Expected: >😀🤣< and got >😀🤣<
# Inserting from REST and comparing with REST Get:
REST(SUCCESS) | Expected: >😀🤣< and got >😀🤣<
```

**Comment by niolap** [comment]
> Moreover, it's not something that hard to fix. So I'd suggest to include it into 0.10.

Ok. Shifted back to 0.10.0.

**Comment by cxxman** [comment]
Found this code in the JSON library:
https://github.com/nlohmann/json/blob/ec7a1d834773f9fee90d8ae908a0c9933c5646fc/src/json.hpp#L4604-L4697

So looks like we really don't need to change anything.
