### ISSUE TITLE
Create database with uuid option

### ISSUE THREAD

**Issue by niolap** [siodb/siodb#155]
A WITH option in the create database statement. 
E.g. `create database DB1 with UUID='01e7f016-b158-11eb-8529-0242ac130003'`;

**Purpose:** before executing this command one should have created the filesystem `<data_dir>/01e7f016-b158-11eb-8529-0242ac130003` before. Thus the data files would be completely isolated from the other databases.

**Comment by cxxman** [comment]
@niolap Actually, database dir path is `<data-dir>/db-<uuid>` (note prefix `db-`).

**Comment by cxxman** [comment]
@niolap Some changes: the statement you'll need to use should be like this:
```sql
CREATE DATABASE dbname WITH uuid='01e7f016-b158-11eb-8529-0242ac130003', data_directory_must_exist=true
```
Please note additional attribute `data_directory_must_exist` that you'll need to use.

**Comment by cxxman** [comment]
@niolap I've merged implementation into master, there are few unit tests. I leave up to you to test this more and add SQL tests.

**Comment by niolap** [comment]
@cxxman I take those tests over. Thank you.

**Comment by niolap** [comment]
@cxxman why having `data_directory_must_exist` has an option instead of automatically detected and created if it not exists?

**Comment by cxxman** [comment]
@niolap it will do it by default, if option not specified, or if option explicitly set to `false`. But this option let you additionally ensure the workflow you've mentioned. I.e. Siodb will surely fail creating database if for some reason directory does not already exists. Otherwise it would silently create directory, but it will be on the same filesystem. But as I understood, you want directory to be pre-created mount of another filesystem.

**Comment by niolap** [comment]
@cxxman If we create a database like this:

```bash
mkdir -p <data_dir>/db-fc8225e6-6068-4a3e-b55f-0d4c3326a2cb
```

```sql
create database DB3
with uuid = 'fc8225e6-6068-4a3e-b55f-0d4c3326a2cb',
data_directory_must_exist = false
```

What means exactly `data_directory_must_exist = false`?

1. Data directory may or may not exists
2. Data directory must not exist

Because currently, the behavior is (1) but not sure is what you had in mind.

**Comment by cxxman** [comment]
option 1

**Comment by niolap** [comment]
```database-uuid | INFO | SUCCESS: Test passed in 1.71 minutes```
