### ISSUE TITLE
 GET all rows returns 404 for the empty table, even when the table exists

### ISSUE THREAD

**Issue by cxxman** [siodb/siodb#158]
@cxxman tested a bit and I think we have a regression. For instance now, the REST GET request on a table returns a table not exist error, even when the table exists:

```bash
$ ./build/release/bin/siocli -i ./tests/share/private_key --user root -r
Siodb SQL Client v.0.10.0
Compiled on May 31 2021 13:36:03
Copyright (C) 2019-2021 Siodb GmbH. All rights reserved.

siocli> select * from db1.table1 ;

Connected to localhost:50000

TRID                COL1
------------------- ----------------------------------------

Row(s): 0

Elapsed time: 14 ms.
```

And the result from curl:

```bash
curl -k https://root:${TOKEN}@localhost:50443/databases/db1/tables/table1/rows
```

Returns:

```bash
{"status":404,"rows":[]}
```

A few commits ago it returned 200. I know it because the test `tests/scenarios/rest_codes_returned/run.sh` was running successfully. And now it's not working anymore.

But if I insert a row, now I have a code 200.  So I think we should get back to the previous code 200 when no row exists. Because it returns a result set of no row successfully. It is just that there is no row. 

EDIT: After thinking deeper, maybe is not too bad to have 404 when no row is returned.

_Originally posted by @niolap in https://github.com/siodb/siodb/issues/133#issuecomment-851588968_

**Comment by cxxman** [comment]
I think it's here https://github.com/siodb/siodb/commit/99286c6ad539ddf440d9b124acdfa0128ed1b622
Maybe it was intended to fix #131
I think 200 is more correct if you request all rows even if no rows in the table, but it is reasonable to have 404 if you've requested a single row and it doesn't exist. 
@niolap what do you think of such solution?

**Comment by niolap** [comment]
@cxxman "what do you think of such solution?" => the way to go.
I made it wrong in commit 99286c6

**Comment by cxxman** [comment]
ok, I have fixed it. I was trying and for me your test script was working. Please recheck yourself.

**Comment by niolap** [comment]
works as expected
