### ISSUE TITLE
Set Access-Control-Allow-Origin to star

### ISSUE THREAD

**Issue by niolap** [siodb/siodb#190]
https://stackoverflow.com/questions/29418478/go-gin-framework-cors

**Comment by cxxman** [comment]
@niolap This should be configuration option, like `rest_server.cors_origins` (comma-separated list of values), everyone I've seen so far do it this way. It is generally unsafe to always allows any origin by default. Option value specified in the sample config file should be `*`, but default allowed origins for the case when option is not specified must be empty.
