### ISSUE TITLE
Question: POST/PUT string in INT column should be accepted?

### ISSUE THREAD

**Issue by niolap** [siodb/siodb#191]
POST/PUT of `[{"col_int": "2"}]` return 400 from the IOMgr few commits ago. Because the target column was an INT. Only `[{"col_int": 2}]` was accepted with the value as an INT and not a string. But now POST/PUT of `[{"col_int": "2"}]` return 201/200 from the IOMgr.

Question: is it normal and expected?
- If yes: I will modify the test accordingly (allocate the issue to me)
- If no: something must be changed in the IOMgr

**Comment by cxxman** [comment]
@niolap It should be discussed and decided, which behavior is correct. The point is that concrete string you are passing here is such that successful conversion from "string" to "int" is possible, and that's what happens. I think if you try another string like "aaa" it will get you 400. Personally I think current behavior is acceptable. If you want it strongly rejecting strings when inserting to numeric columns, then yes, some fix needs to be done.

**Comment by cxxman** [comment]
@niolap I've checked a bit more and found out that some other libraries generate very large numbers that doesn't fit JavaScript number type as strings in JSON. For example, protobuf json serializer does this for 64-bit integers. So I think decision should be it is ok to have string as long as conversion from string to numeric type exists.
So I suggest to leave things as is in the `iomgr` and modify the test. Strings which can be converted to number should pass, and those which are not - should fail.

**Comment by cxxman** [comment]
@niolap I've updated current test. I recommend to add more tests like this which insert/update floating point column with convertable and non-convertable strings.

**Comment by niolap** [comment]
@cxxman good, I also think that's ok to have a string as long as conversion from string to numeric type exists. Thank you for the test update.
