### ISSUE TITLE
No drivers

### ISSUE THREAD

**Issue by manonthemat** [siodb/siodb#39]
The links to the Rust and Golang drivers are 404ing.

Are these repos public?

**Comment by niolap** [comment]
Hi @manonthemat,
Thank you for noticing.
I have changed the repo to "public" and added other programming languages as a place holder.
For the time being, we have a Rust drive that I'll publish on next Tuesday and a Go driver almost ready that I will publish in 4 weeks.
Also, you can add a star to the driver repo of your preferred programming language. That will let us know on which one we should focus next.
Please let me know should you have more questions 😄

**Comment by niolap** [comment]
@manonthemat, I release the Rust driver here: https://github.com/siodb/siodb-rust-driver
Please let me know should you need more details 😄
