### ISSUE TITLE
SQL Dump feature to backup the database content

### ISSUE THREAD

**Issue by niolap** [siodb/siodb#47]
We need to iterate over every database, tables, and columns to generate SQL commands (`create database`, `create table`, `insert into`). It should be a feature from siocli because siodb is the front-end to interact with the database. Thus we should reuse the code from `siocli`. 

To instruct siocli to execute an export, we need two new options in the `siocli`:
-  `--export-all` or `-E` - exports data from all databases
- `--export DATABASE_NAME` or `-e DATABASE_NAME` - exports data from the specified database
If we have on the mentioned above options presents, we perform the export, otherwise we simply start siocli as usual.

The dump must be on a SQL format ready to be replayed "as-is" in an empty Siodb instance. And those SQL commands must be written into the stdout.

**Example:**
```bash
$ siocli --user=root --export-all
-- Siodb SQL dump
-- Hostname: <server_name>
-- Instance: <instance_name>
-- Timestamp: <current_timestmap e.g. 08.06.2020 12:39:12>
CREATE DATABASE TEST1 ;
CREATE TABLE TEST1.TABLE1 (
COL1 TEXT, 
COL2 INT
);
INSERT INTO TABLE TEST1.TABLE1 ('whatever', 34);
INSERT INTO TABLE TEST1.TABLE1 ('whatever', 53);
CREATE TABLE TEST1.TABLE2 (
COL1 TEXT, 
COL2 INT, 
COL2 TEXT);
INSERT INTO TABLE TEST1.TABLE2 ....
INSERT INTO TABLE TEST1.TABLE2 ....
CREATE DATABASE TEST2;
CREATE TABLE TEST2.TABLE1 ...;
.....
```
## Handle TRID holes

It is most likely that a table has holes in its TRID sequence over time because of DML activity. As Siodb automatically generates the TRID by incrementing it at insert time, we must set the TRID at the correct number when importing data so that the generated TRID at import time is bound with the TRID that on the source. 
To manage this TRID positioning we'll use the following command:

```sql
ALTER TABLE [<database_name>.]<table_name> SET NEXT_TRID = <BIGINT> ;
```

The export feature must position this TRID between holes to reproduce the proper TRID sequence at import time.

This feature will be part of the issue #49.

## Lock for further import

While importing, we must lock the database. When the import finishes, the database must be unlocked. Thus we must integrate those commands into the SQL dump file:

```sql
LOCK DATABASE <database_name> ;
UNLOCK <database_name> ;
```

This feature will be part of another issue.

## Full example

Let's assume that we have one database DBTEST, which as one table TABLE1 with five rows (having one hole in the TRID sequence).
Here is how would looks like the SQL dump:

```sql
CREATE DATABASE dbtest WITH cipher_id = 'aes128', cipher_key_seed = 'fksgksgjrekgjerkglerjg' ;
LOCK DATABASE dbtest ;
CREATE TABLE dbtest.table1 ( firstname text, lastname text, age int ) ;
INSERT INTO dbtest.table1 ( 'Fname1', 'Lname1', 23 ) ; -- Trid = 1
INSERT INTO dbtest.table1 ( 'Fname2', 'Lname2', 54 ) ; -- Trid = 2
INSERT INTO dbtest.table1 ( 'Fname3', 'Lname3', 27 ) ; -- Trid = 3
ALTER TABLE dbtest.table1 SET NEXT_TRID = 16 ;
INSERT INTO dbtest.table1 ( 'Fname4', 'Lname4', 83 ) ; -- Trid = 16
INSERT INTO dbtest.table1 ( 'Fname5', 'Lname5', 47 ) ; -- Trid = 17
ALTER TABLE dbtest.table1 SET NEXT_TRID = 18 ;
UNLOCK dbtest ;
```

**Comment by cxxman** [comment]
Implemented w/o locking and special character handling. I suggest to create separate tasks (if not yet created) for locking and special character handling.

**Comment by niolap** [comment]
Works as expected.
Thank you @Demilivor 👍
