### ISSUE TITLE
Add build instructions for the Oat++ library

### ISSUE THREAD

**Issue by cxxman** [siodb/siodb#67]
Update `Build.md` with instructions for building Oat++.

**Comment by lganzzzo** [comment]
Hello @cxxman ,

Please feel free to contact me in case of questions related to Oat++,- I'll be happy to help!

Following up your question (in Oat++ devs chat) about the OpenSSL -
All that needs to be done is to build oatpp-openssl adaptor - so we can cooperate on this one.

Regards,
Leonid

**Comment by cxxman** [comment]
Hi @lganzzzo , unfortunately, we don't have capacity to spend time on "building" (in fact, developing) oatpp-openssl adapter. We are looking for something already working and stable. We have made decision to not use oatpp either in favor of some other library (I think it will be [Microsoft C++ REST SDK](https://github.com/microsoft/cpprestsdk) ) or writing the component we've planned to use it for in some other programming language like Go.

**Comment by lganzzzo** [comment]
Hey,

Thanks for the update/feedback!

Regards,
Leonid
