### ISSUE TITLE
Physical backup/restore doesn't work

### ISSUE THREAD

**Issue by cxxman** [siodb/siodb#88]
Make physical backup like this (after having shutdown the instance properly):
```bash
tar -zcvf backup_siodb_instance_siodb000_`date +"%y-%m-%d_%H-%M-%s"`.tar.gz /var/lib/siodb/siodb000/data
```
Then try to restore like that:
```bash
tar -pxvzf backup_siodb_instance_siodb000_20-10-12_09-29-1602494985.tar.gz
```
When instance starts again, for some reason it creates a new system database. It seems that it doesn't detect the current data files.

**Comment by cxxman** [comment]
@niolap I could not reproduce this. Am I missing something? I have create test (`issues/gh-88-physical-backup]`). Please review it and make corrections, if you thing it is incorrect. Then returns task to me. If test is correct, then it seems to pass, so just close the task.

**Comment by niolap** [comment]
@cxxman ok, unable to reproduce, it works well now 👍
